### ISSUE TITLE
Prophet like strategy

### ISSUE THREAD

**Issue by femtotrader** [ysdede/jesse_strategies#8]
Hello,

I'm new to Jesse.
I wonder if a Prophet like strategy couldn't be written
https://medium.com/geekculture/what-happens-if-you-day-trade-crypto-with-facebook-prophet-84df66c31657
Any opinion about it ?

Kind regards

**Comment by ysdede** [comment]
Hey, I played with Prophet this year. I abandoned it because the results were insufficient for me, but this could be due to my lack of experience.
Yes, you can use Jesse with any AI/ML project. You can use Jesse's candle database for training and then signal Jesse to open close trades.
I have a jupyter notebook about it, but it's out of date and a mess. I might upload it after I get it to work.

PS: Prophet predicted that it could go up or down like a crypto influencer.

![image](https://user-images.githubusercontent.com/5496750/205111228-95140b3e-b522-49dd-932c-b626105bbd04.png)

**Comment by femtotrader** [comment]
A Jupyter notebook with data from eodhistoricaldata.com can be found at https://github.com/marcosan93/Medium-Misc-Tutorials/blob/main/Crypto-Tutorials/Intraday-Trading-FBProphet.ipynb it will be great if you could share yours and possibly also Jesse strategy.
